import { Providers } from '@/components/providers/Providers';
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider } from 'next-intl';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// RootLayout now accepts 'children' and 'params'
export default async function RootLayout({
    children,
    params,
}: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    // Ensure that the incoming `locale` is valid
    const { locale } = await params;
    // Setting the locale for Next-Intl
    setRequestLocale(locale);
    return (
        <html lang={locale}>
            <body
                className={cn(geistSans.variable, geistMono.variable, "m-0 p-0 box-border")}
                suppressContentEditableWarning suppressHydrationWarning
            >
                <NextIntlClientProvider locale={locale} >
                    <Providers>
                        <Toaster closeButton position='top-right' richColors />
                        {children}
                    </Providers>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
